name: Lint

on:
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00
        with:
          go-version-file: go.mod
          cache: false

      - name: Golangci lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.0
          args: --verbose

      - name: Markdown lint
        uses: docker://avtodev/markdown-lint:v1@sha256:6aeedc2f49138ce7a1cd0adffc1b1c0321b841dc2102408967d9301c031949ee
        with:
          config: '.markdownlint.yml'
          args: '**/*.md'

      - name: Typo lint
        uses: crate-ci/typos@0c17dabcee8b8f1957fa917d17393a23e02e1583 # v1.36.3
        with:
          config: .typos.toml

      - name: Example lint
        run: make validate-examples

      - name: Run tests
        run: make test
